# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0002_auto_20170705_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='статус',
            field=models.CharField(choices=[('Выполнено', 'Выполнено')], default=0, max_length=125),
            preserve_default=False,
        ),
    ]
