# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0003_feedback_статус'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='статус',
            field=models.CharField(choices=[('Выполнено', 'Выполнено')], default='Выполнено', max_length=125),
        ),
    ]
