# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0005_auto_20170705_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='статус',
            field=models.CharField(choices=[('Отправлено в работу', 'Отправлено в работу')], default='Отправлено в работу', max_length=125),
        ),
    ]
