# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0007_auto_20170705_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['create'], 'verbose_name': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='статус',
            field=models.CharField(choices=[('В работе', 'В работе'), ('Выполнено', 'Выполнено')], default='В работе', max_length=125),
        ),
    ]
