# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0008_auto_20170705_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Заявки'},
        ),
    ]
