# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0011_feedback_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback_done',
            old_name='номер_заявки',
            new_name='Номер_заявки',
        ),
    ]
