# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0012_auto_20170710_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_done',
            name='done_time',
            field=models.DateTimeField(null=True),
        ),
    ]
