# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0013_feedback_done_done_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_done',
            name='done_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
