# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0015_auto_20170710_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_done',
            name='cтатус',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='done', to='primer.Feedback'),
        ),
    ]
