# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0017_auto_20170710_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback_done',
            old_name='Номер_заявки',
            new_name='Атрибуты_заявки',
        ),
    ]
