# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 09:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Сотрудники', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Компьютеры_оргтехника',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('категория', models.CharField(choices=[('Компьютер', 'Компьютер'), ('Переферийное оборудование', 'Переферийное оборудование'), ('Сетевое оборудование', 'Сетевое оборудование'), ('Комплектующие', 'Комплектующие'), ('Расходный материал', 'Расходный материал'), ('Аксессуары', 'Аксессуары'), ('Бытовая техника', 'Бытовая техника'), ('Прочее', 'Прочее')], max_length=125)),
                ('наименование', models.CharField(choices=[('#### КОМПЬЮТЕР ####', '#### КОМПЬЮТЕР ####'), ('Моноблок', 'Моноблок'), ('Сиcтемный блок', 'Системный блок'), ('Монитор', 'Монитор'), ('Материнская плата', 'Материнская плата'), ('Процессор', 'Процессор'), ('#### ПЕРЕФЕРИЙНОЕ ОБОРУДОВАНИЕ ####', '#### ПЕРЕФЕРИЙНОЕ ОБОРУДОВАНИЕ ####'), ('Источник бесперебойного питания', 'Источник бесперебойного питания'), ('Принтер-лазерный', 'Принтер-лазерный'), ('Принтер-струйный', 'Принтер-струйный'), ('Мфу', 'Мфу'), ('Сканер', 'Сканер'), ('Флешка', 'Флешка'), ('Факс', 'Факс'), ('#### АКСЕССУАРЫ ####', '#### АКСЕССУАРЫ ####'), ('Мышка', 'Мышка'), ('Клавиатура', 'Клавиатура'), ('Сетевой фильтр', 'Сетевой фильтр'), ('#### РАСХОДНЫЙ МАТЕРИАЛ ####', '#### РАСХОДНЫЙ МАТЕРИАЛ ####'), ('Картридж', 'Картридж'), ('Коннекторы', 'Коннекторы'), ('Интернет кабель', 'Интернет кабель'), ('#### СЕТЕВОЕ ОБОРУДОВАНИЕ ####', '#### СЕТЕВОЕ ОБОРУДОВАНИЕ ####'), ('Сетевая карта', 'Сетевая карта'), ('Роутер', 'Роутер'), ('Маршрутизатор', 'Маршрутизатор'), ('#### КОМПЛЕКТУЮЩИЕ ####', '#### КОМПЛЕКТУЮЩИЕ ####'), ('Жесткий диск', 'Жесткий диск'), ('Внешний жесткий диск', 'Внешний жесткий диск'), ('Процессор', 'Процессор'), ('Блок питания', 'Блок питания'), ('Оперативная память', 'Оперативная память'), ('#### БЫТОВАЯ ТЕХНИКА ####', '#### БЫТОВАЯ ТЕХНИКА ####'), ('Кондиционер', 'Кондиционер'), ('Мобильный кондиционер', 'Мобильный кондиционер'), ('Мультисплит-внешний', 'Мультисплит-внешний'), ('Мультисплит-внутренний', 'Мультисплит-внутренний'), ('Комплект сплит-система', 'Комплект сплит-система'), ('Уничтожитель документов', 'Уничтожитель документов'), ('#### ПРОЧЕЕ ####', '#### ПРОЧЕЕ ####'), ('Накопитель на ЖМД', 'Накопитель на ЖМД'), ('ИК-термометр', 'ИК-термометр'), ('Фотоаппарат', 'Фотоаппарат'), ('Система многоканальной записи', 'Система многоканальной записи'), ('Электрический воздухонагреватель', 'Электрический воздухонагреватель'), ('Data Logger', 'Data Logger')], max_length=125)),
                ('модель_устройства', models.CharField(max_length=50)),
                ('год_выпуска', models.DateField(blank=True, default=None, null=True)),
                ('описание', models.TextField(blank=True, default=None, help_text='Максимальное кол-во символов 500', max_length=500, null=True)),
                ('ед_изм', models.CharField(choices=[('шт', 'шт'), ('м', 'м')], default='шт', max_length=10)),
                ('количество', models.IntegerField(default='', help_text='укажите кол-во', validators=[django.core.validators.MaxValueValidator(125), django.core.validators.MinValueValidator(0)])),
                ('статус', models.CharField(choices=[('В наличии', 'В наличии'), ('Рабочее состояние', 'Рабочее состояние'), ('Заменить срочно', 'Заменить срочно'), ('Не работает', 'Не работает'), ('Требуется замена', 'Требуется замена'), ('Требуется ремонт', 'Требуется ремонт'), ('Требуется диагностика', 'Требуется диагностика'), ('Требуется закупить', 'Требуется закупить'), ('В ремонте', 'В ремонте'), ('На складе', 'На складе')], max_length=125)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата_создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='дата_обновления')),
                ('списано', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'компьютерная и оргтехника',
                'verbose_name_plural': 'компьютеры и оргтехника',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Списанное_оборудование',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('причина_списания', models.CharField(blank=True, max_length=125)),
                ('адрес_местонахождения', models.CharField(choices=[('улица Молодцова 9', 'улица Молодцова 9'), ('Ясный проезд 4к3', 'Ясный проезд 4к3'), ('проезд Дежнева 22к4', 'проезд Дежнева 22к4'), ('проезд Дежнева 9к2', 'проезд Дежнева 9к2'), ('проезд Дежнева 34 - склад', 'проезд Дежнева 34 - склад'), ('ОДС-1 ул. - Полярная 15к3', 'ОДС-1 ул. - Полярная 15к3'), ('ОДС-2 ул. - Полярная 15к3', 'ОДС-2 ул. - Полярная 15к3'), ('ОДС-3 ул. - Полярная 15к3', 'ОДС-3 ул. - Полярная 15к3'), ('ОДС-4 ул. - Шокальского 3к1', 'ОДС-4 ул. - Шокальского 3к1'), ('ОДС-5 ул. - Шокальского 3к1', 'ОДС-5 ул. - Шокальского 3к1'), ('ОДС-6 ул. - Дежнева 9к2', 'ОДС-6 ул. - Дежнева 9к2'), ('ОДС-7 ул. - Полярная 9к2', 'ОДС-7 ул. - Полярная 9к2'), ('Вилюйская ул. строение5', 'Вилюйская ул. строение5')], max_length=125)),
                ('date_end', models.DateTimeField(auto_now_add=True, verbose_name='дата_списания')),
            ],
            options={
                'verbose_name': 'списанное оборудование',
                'verbose_name_plural': 'списанное оборудование',
            },
        ),
        migrations.CreateModel(
            name='Справочник_мест_установки',
            fields=[
                ('id_места_установки', models.AutoField(primary_key=True, serialize=False)),
                ('одс', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=125)),
                ('адрес', models.CharField(choices=[('улица Молодцова 9', 'улица Молодцова 9'), ('Ясный проезд 4к3', 'Ясный проезд 4к3'), ('проезд Дежнева 22к4', 'проезд Дежнева 22к4'), ('проезд Дежнева 9к2', 'проезд Дежнева 9к2'), ('проезд Дежнева 34 - склад', 'проезд Дежнева 34 - склад'), ('ОДС-1 ул. - Полярная 15к3', 'ОДС-1 ул. - Полярная 15к3'), ('ОДС-2 ул. - Полярная 15к3', 'ОДС-2 ул. - Полярная 15к3'), ('ОДС-3 ул. - Полярная 15к3', 'ОДС-3 ул. - Полярная 15к3'), ('ОДС-4 ул. - Шокальского 3к1', 'ОДС-4 ул. - Шокальского 3к1'), ('ОДС-5 ул. - Шокальского 3к1', 'ОДС-5 ул. - Шокальского 3к1'), ('ОДС-6 ул. - Дежнева 9к2', 'ОДС-6 ул. - Дежнева 9к2'), ('ОДС-7 ул. - Полярная 9к2', 'ОДС-7 ул. - Полярная 9к2'), ('Вилюйская ул. строение5', 'Вилюйская ул. строение5')], max_length=125)),
                ('кабинет', models.CharField(blank=True, choices=[('#### МОЛОДЦОВА 9 ####', '#### МОЛОДЦОВА 9 ####'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('#### ЯСНЫЙ ПРОЕЗД 4к3 ####', '#### ЯСНЫЙ ПРОЕЗД 4к3 ####'), ('21', '21'), ('20', '20'), ('19', '19'), ('18', '18'), ('17', '17'), ('16', '16'), ('#### ДЕЖНЕВА 9к2 ####', '#### ДЕЖНЕВА 9к2 ####'), ('8', '8'), ('7', '7'), ('6', '6'), ('1', '1')], max_length=125)),
                ('фио_ответственного', models.ForeignKey(help_text='Выберите сотрудника ответственного за данный кабинет', on_delete=django.db.models.deletion.CASCADE, to='Сотрудники.Сотрудники')),
            ],
            options={
                'verbose_name': 'справочник мест установки',
                'verbose_name_plural': 'справочник мест установки',
            },
        ),
        migrations.CreateModel(
            name='Уникальный_номер',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('инвентарный_номер', models.CharField(blank=True, default=None, max_length=35, unique=True)),
            ],
            options={
                'verbose_name': 'инвентарный номер',
                'verbose_name_plural': 'инвентарные номера',
            },
        ),
        migrations.CreateModel(
            name='Фиксация_перемещения',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('причина_перемещения', models.TextField(blank=True, default=None, help_text='Максимальное кол-во символов 250', max_length=250, null=True)),
                ('куда_переместили', models.CharField(choices=[('#### МОЛОДЦОВА 9 ####', '#### МОЛОДЦОВА 9 ####'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('#### ЯСНЫЙ ПРОЕЗД 4к3 ####', '#### ЯСНЫЙ ПРОЕЗД 4к3 ####'), ('21', '21'), ('20', '20'), ('19', '19'), ('18', '18'), ('17', '17'), ('16', '16'), ('#### ДЕЖНЕВА 9к2 ####', '#### ДЕЖНЕВА 9к2 ####'), ('8', '8'), ('7', '7'), ('6', '6'), ('1', '1')], max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата_перемещения')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='дата_обновления')),
                ('инвентарный_номер', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Computers_and_other_equipment.Уникальный_номер')),
                ('куда_адрес', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adress', to='Computers_and_other_equipment.Справочник_мест_установки')),
                ('наименование', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computers_and_other_equipment.Компьютеры_оргтехника')),
                ('ответственное_лицо', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Сотрудники.Сотрудники')),
                ('откуда_переместили', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computers_and_other_equipment.Справочник_мест_установки')),
            ],
            options={
                'verbose_name': 'перемещение компьютерной и оргтехники',
                'verbose_name_plural': 'компьютеры и оргтехника - фиксация_перемещения',
            },
        ),
        migrations.AddField(
            model_name='списанное_оборудование',
            name='инвентарный_номер',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Computers_and_other_equipment.Уникальный_номер'),
        ),
        migrations.AddField(
            model_name='списанное_оборудование',
            name='наименование',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computers_and_other_equipment.Компьютеры_оргтехника'),
        ),
        migrations.AddField(
            model_name='компьютеры_оргтехника',
            name='barcode',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Computers_and_other_equipment.Уникальный_номер', verbose_name='инвентарный_номер'),
        ),
        migrations.AddField(
            model_name='компьютеры_оргтехника',
            name='id_места_установки',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computers_and_other_equipment.Справочник_мест_установки'),
        ),
        migrations.AddField(
            model_name='компьютеры_оргтехника',
            name='материально_ответственный',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Сотрудники.Сотрудники'),
        ),
    ]
