# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Computers_and_other_equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='компьютеры_оргтехника',
            name='картридж',
            field=models.CharField(blank=True, max_length=125),
        ),
    ]
