# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Computers_and_other_equipment', '0002_компьютеры_оргтехника_картридж'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge_list',
            fields=[
                ('catlis_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер списка')),
            ],
            options={
                'verbose_name': 'Список - принтер, картридж',
                'verbose_name_plural': 'Список - принтеры, картриджи',
            },
        ),
        migrations.CreateModel(
            name='Картридж',
            fields=[
                ('cartridge_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер картриджа')),
                ('cartridge_model', models.CharField(max_length=100, verbose_name='Модель картриджа')),
            ],
            options={
                'verbose_name': 'Картридж',
                'verbose_name_plural': 'Картриджи',
            },
        ),
        migrations.CreateModel(
            name='Принтер',
            fields=[
                ('printer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер принтера')),
                ('printer_model', models.CharField(max_length=100, verbose_name='Модель принтера')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
            },
        ),
        migrations.AddField(
            model_name='cartridge_list',
            name='catlis_cartridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computers_and_other_equipment.Картридж', verbose_name='Список картриджей'),
        ),
        migrations.AddField(
            model_name='cartridge_list',
            name='catlis_printerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computers_and_other_equipment.Принтер', verbose_name='Список принтеров'),
        ),
    ]
