# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Computers_and_other_equipment', '0003_auto_20170714_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartridge_list',
            options={'verbose_name': 'cписок - принтер, картридж', 'verbose_name_plural': 'cписок - принтеры, картриджи'},
        ),
        migrations.AlterModelOptions(
            name='картридж',
            options={'verbose_name': 'картридж', 'verbose_name_plural': 'картриджи'},
        ),
        migrations.AlterModelOptions(
            name='принтер',
            options={'verbose_name': 'принтер', 'verbose_name_plural': 'принтеры'},
        ),
        migrations.AddField(
            model_name='cartridge_list',
            name='adress_to_dislacate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Computers_and_other_equipment.Справочник_мест_установки', verbose_name='место установки'),
            preserve_default=False,
        ),
    ]
