# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Computers_and_other_equipment', '0004_auto_20170715_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartridge_list',
            old_name='adress_to_dislacate',
            new_name='address_to_dislacate',
        ),
    ]
