# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Computers_and_other_equipment', '0005_auto_20170715_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_of_printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_model', models.CharField(max_length=100, verbose_name='Модель принтера')),
                ('cartridge_model', models.CharField(max_length=100, verbose_name='Модель картриджа')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('address_to_dislacate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computers_and_other_equipment.Справочник_мест_установки', verbose_name='место установки')),
            ],
        ),
    ]
