# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Computers_and_other_equipment', '0008_cartridge_list_наименование'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridge_list',
            name='модель_картридж',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='Computers_and_other_equipment.Компьютеры_оргтехника'),
            preserve_default=False,
        ),
    ]
