# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Южное_Медведково', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='справочник_материалов',
            fields=[
                ('id_материала', models.AutoField(primary_key=True, serialize=False)),
                ('наименование_материала', models.CharField(max_length=150)),
                ('примечание', models.TextField(max_length=650)),
            ],
            options={
                'verbose_name': ' справочник материал',
                'verbose_name_plural': 'справочник материалов',
            },
        ),
        migrations.AddField(
            model_name='мкд',
            name='требуемый_материал',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Южное_Медведково.справочник_материалов'),
            preserve_default=False,
        ),
    ]
