# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Южное_Медведково', '0002_auto_20170721_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='справочник_материалов',
            name='категория',
            field=models.CharField(choices=[('Плиточные работы', 'Плиточные работы'), ('Штукатурно-малярные работы', 'Штукатурно-малярные работы'), ('Фасадные работы', 'Фасадные работы')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='справочник_материалов',
            name='наименование_материала',
            field=models.CharField(choices=[('Плиточный клей', 'Плиточный клей'), ('Штукатурная смесь ротбанд', 'Штукатурная смесь ротбанд'), ('Краска белая алкидная', 'Краска белая алкидная')], max_length=150),
        ),
    ]
