# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Южное_Медведково', '0003_auto_20170721_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='справочник_материалов',
            name='примечание',
            field=models.TextField(blank=True, max_length=650),
        ),
    ]
