# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Южное_Медведково', '0004_auto_20170721_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='мкд',
            name='фотоматериал',
            field=models.ImageField(blank=True, upload_to='users_photo/%d.%m.%Y/'),
        ),
    ]
