# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 14:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Южное_Медведково', '0005_auto_20170721_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='справочник_материалов',
            name='единица_измерения',
            field=models.CharField(choices=[('кг', 'кг'), ('шт', 'шт'), ('п.м.', 'п.м.'), ('см', 'см')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='справочник_материалов',
            name='кол_во',
            field=models.IntegerField(default=0, help_text='значение не может быть раным: 0', validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)]),
        ),
    ]
