# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Южное_Медведково', '0006_auto_20170721_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='мкд',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='users_photo/%d.%m.%Y/'),
        ),
        migrations.AlterField(
            model_name='справочник_материалов',
            name='наименование_материала',
            field=models.CharField(choices=[('Плиточный клей', 'Плиточный клей'), ('Плитка 40х40', 'Плитка 40х40'), ('Штукатурная смесь ротбанд', 'Штукатурная смесь ротбанд'), ('Краска белая алкидная', 'Краска белая алкидная')], max_length=150),
        ),
    ]
