# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Южное_Медведково', '0007_auto_20170722_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='мкд',
            name='image',
        ),
    ]
