# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Южное_Медведково', '0008_remove_мкд_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='мкд',
            old_name='категория',
            new_name='вид_работ',
        ),
    ]
